<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-3-12
 * Time: 10:56
 */

namespace app\home\controller;


use think\Controller;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(session('member_id')==null){
           $this->redirect('login/index');
        }
    }
}